spring:
  application:
    name: jxrxfxre_study
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}